### ISSUE TITLE
missing .pkl on first round of training

### ISSUE THREAD

**Issue by dmarx** [autonomousvision/stylegan_xl#11]
Working through the pokemon demo. I think there might be a step missing in the instructions to download pre-trained weights. Encountered the following error attempting to run train.py on first round of progressive training:

```
(sgxl) user@host:~/dmarx/stylegan_xl$ python train.py --outdir=./training-runs/pokemon --cfg=stylegan3-t --data=../../datasets/pokemon16.zip     --gpus=4 --batch=64 --mirror=1 --snap 10 --batch-gpu 16 --kimg 10000 --stem --syn_layers 10

Training options:
{
  "G_kwargs": {
    "class_name": "training.networks_stylegan3_resetting.Generator",
    "z_dim": 64,
    "w_dim": 512,
    "mapping_kwargs": {
      "num_layers": 2,
      "rand_embedding": false
    },
    "channel_base": 65536,
    "channel_max": 1024,
    "magnitude_ema_beta": 0.9977843871238888,
    "num_layers": 10
  },
  "D_kwargs": {
    "class_name": "pg_modules.discriminator.ProjectedDiscriminator",
    "backbones": [
      "deit_base_distilled_patch16_224",
      "tf_efficientnet_lite0"
    ],
    "diffaug": true,
    "interp224": true,
    "backbone_kwargs": {
      "cout": 64,
      "expand": true,
      "proj_type": 1,
      "num_discs": 4,
      "cond": false
    }
  },
  "G_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08,
    "lr": 0.0025
  },
  "D_opt_kwargs": {
    "class_name": "torch.optim.Adam",
    "betas": [
      0,
      0.99
    ],
    "eps": 1e-08,
    "lr": 0.002
  },
  "loss_kwargs": {
    "class_name": "training.loss.ProjectedGANLoss",
    "blur_init_sigma": 2,
    "blur_fade_kimg": 300,
    "pl_weight": 2.0,
    "pl_no_weight_grad": true,
    "style_mixing_prob": 0.0,
    "cls_weight": 0.0,
    "cls_model": "deit_small_distilled_patch16_224",
    "train_head_only": false
  },
  "data_loader_kwargs": {
    "pin_memory": true,
    "prefetch_factor": 2,
    "num_workers": 3
  },
  "training_set_kwargs": {
    "class_name": "training.dataset.ImageFolderDataset",
    "path": "../../datasets/pokemon16.zip",
    "use_labels": false,
    "max_size": 4729,
    "xflip": true,
    "resolution": 16,
    "random_seed": 0
  },
  "num_gpus": 4,
  "batch_size": 64,
  "batch_gpu": 16,
  "metrics": [
    "fid50k_full"
  ],
  "total_kimg": 10000,
  "kimg_per_tick": 4,
  "image_snapshot_ticks": 10,
  "network_snapshot_ticks": 10,
  "random_seed": 0,
  "ema_kimg": 20.0,
  "restart_every": 999999999,
  "run_dir": "./training-runs/pokemon/00000-stylegan3-t-pokemon16-gpus4-batch64"
}

Output directory:    ./training-runs/pokemon/00000-stylegan3-t-pokemon16-gpus4-batch64
Number of GPUs:      4
Batch size:          64 images
Training duration:   10000 kimg
Dataset path:        ../../datasets/pokemon16.zip
Dataset size:        4729 images
Dataset resolution:  16
Dataset labels:      False
Dataset x-flips:     True

Creating output directory...
Launching processes...
Loading training set...

Num images:  9458
Image shape: [3, 16, 16]
Label shape: [0]

Constructing networks...
Traceback (most recent call last):
  File "train.py", line 362, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 347, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 106, in launch_training
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/miniconda/envs/sgxl/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/user/dmarx/stylegan_xl/train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/user/dmarx/stylegan_xl/training/training_loop.py", line 170, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/home/user/dmarx/stylegan_xl/dnnlib/util.py", line 303, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/home/user/dmarx/stylegan_xl/dnnlib/util.py", line 298, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/home/user/dmarx/stylegan_xl/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/dmarx/stylegan_xl/training/networks_stylegan3_resetting.py", line 583, in __init__
    self.mapping = MappingNetwork(z_dim=z_dim, c_dim=c_dim, w_dim=w_dim, num_ws=self.num_ws, **mapping_kwargs)
  File "/home/user/dmarx/stylegan_xl/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/dmarx/stylegan_xl/training/networks_stylegan3_resetting.py", line 138, in __init__
    with open(embed_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'in_embeddings/tf_efficientnet_lite0.pkl'
```

**Comment by xl-sr** [comment]
went missing thanks to .gitignore, thanks! :)

**Comment by MasterScrat** [comment]
If you encounter this problem again, it's because you need your current working directory to by `stylegan_xl`, else it will fail with the error above.
