### ISSUE TITLE
Code Doesn't Run with cfg=stylegan Because Missing Stylegan2 Loss Function

### ISSUE THREAD

**Issue by 6630507** [autonomousvision/stylegan_xl#17]
loss.py is missing the StyleGAN2 loss function.

Using the command

`python train.py --data ../datasets/scapes-faces-C-32px.zip --outdir results/stem1 --cfg stylegan3-t --gpus 1 --batch 64 --snap 10 --batch-gpu 16 --syn_layers 10`

Results in the error:

`Setting up augmentation...
Distributing across 1 GPUs...
Setting up training phases...
Traceback (most recent call last):
  File "/home/HDD/ml/stylegan_xl/train.py", line 362, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/HDD/anaconda3/envs/sgxl/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/HDD/anaconda3/envs/sgxl/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/HDD/anaconda3/envs/sgxl/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/HDD/anaconda3/envs/sgxl/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/HDD/ml/stylegan_xl/train.py", line 347, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/home/HDD/ml/stylegan_xl/train.py", line 104, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "/home/HDD/ml/stylegan_xl/train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/HDD/ml/stylegan_xl/training/training_loop.py", line 232, in training_loop
    loss = dnnlib.util.construct_class_by_name(device=device, G=G, G_ema=G_ema, D=D, augment_pipe=augment_pipe, **loss_kwargs) # subclass of training.loss.Loss
  File "/home/HDD/ml/stylegan_xl/dnnlib/util.py", line 303, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/home/HDD/ml/stylegan_xl/dnnlib/util.py", line 296, in call_func_by_name
    func_obj = get_obj_by_name(func_name)
  File "/home/HDD/ml/stylegan_xl/dnnlib/util.py", line 289, in get_obj_by_name
    module, obj_name = get_module_from_obj_name(name)
  File "/home/HDD/ml/stylegan_xl/dnnlib/util.py", line 269, in get_module_from_obj_name
    get_obj_from_module(module, local_obj_name) # may raise AttributeError
  File "/home/HDD/ml/stylegan_xl/dnnlib/util.py", line 283, in get_obj_from_module
    obj = getattr(obj, part)
AttributeError: module 'training.loss' has no attribute 'StyleGAN2Loss'`

**Comment by xl-sr** [comment]
you need to add ```--stem```

**Comment by 6630507** [comment]
Awesome, thanks!
