### ISSUE TITLE
Training at 16x16

### ISSUE THREAD

**Issue by taconugget** [autonomousvision/stylegan_xl#32]
When starting a new training with 16x16 stylegan3-t it now errors out, however older trainings that are further along run fine. It seems to only be happening on the initial training without using a stem.

python train.py --outdir=/content/drive/MyDrive/results --cfg=stylegan3-t --data=/content/drive/MyDrive/datasets/16 \
--gpus=1 --batch=32 --mirror=1 --snap 10 --batch-gpu 8 --kimg 280 --syn_layers 10 --metrics=none

Constructing networks...
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 322, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 104, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/training/training_loop.py", line 170, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/dnnlib/util.py", line 303, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/dnnlib/util.py", line 298, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/training/networks_stylegan3_resetting.py", line 583, in __init__
    self.synthesis = SynthesisNetwork(w_dim=w_dim, img_resolution=img_resolution, img_channels=img_channels, **synthesis_kwargs)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/content/drive/MyDrive/colab-sg3XL/stylegan_xl/training/networks_stylegan3_resetting.py", line 495, in __init__
    self.conv_kernel = layer_kwargs['conv_kernel']
KeyError: 'conv_kernel'

**Comment by xl-sr** [comment]
fixed 🙂
