### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'forward_flex'

### ISSUE THREAD

**Issue by leinace1001** [autonomousvision/stylegan_xl#66]
When I train super-resolution stages, a message was thrown out:
Traceback (most recent call last):
  File "train.py", line 338, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 323, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train.py", line 106, in launch_training
    torch.multiprocessing.spawn(fn=subprocess_fn, args=(c, temp_dir), nprocs=c.num_gpus)
  File "/home/ubuntu/MyFiles/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/MyFiles/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ubuntu/MyFiles/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/MyFiles/.local/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ubuntu/user_space/stylegan_xl/train.py", line 49, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/home/ubuntu/user_space/stylegan_xl/training/training_loop.py", line 170, in training_loop
    G = dnnlib.util.construct_class_by_name(**G_kwargs, **common_kwargs).train().requires_grad_(False).to(device) # subclass of torch.nn.Module
  File "/home/ubuntu/user_space/stylegan_xl/dnnlib/util.py", line 303, in construct_class_by_name
    return call_func_by_name(*args, func_name=class_name, **kwargs)
  File "/home/ubuntu/user_space/stylegan_xl/dnnlib/util.py", line 298, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/home/ubuntu/user_space/stylegan_xl/torch_utils/persistence.py", line 104, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/user_space/stylegan_xl/training/networks_stylegan3_resetting.py", line 612, in __init__
    G_stem = legacy.load_network_pkl(f)['G_ema']
  File "/home/ubuntu/user_space/stylegan_xl/legacy.py", line 25, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/home/ubuntu/MyFiles/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VisionTransformer' object has no attribute 'forward_flex'

I use stylegan2, torch ==1.10.1.

**Comment by leinace1001** [comment]
I created a Miniconda environment via conda env create -f environment.yml and now the problem is:
ModuleNotFoundError: No module named 'dill._shims'

**Comment by woctezuma** [comment]
- #55

**Comment by nicholasprimiano** [comment]
> I created a Miniconda environment via conda env create -f environment.yml and now the problem is: ModuleNotFoundError: No module named 'dill._shims'

I ran into this too. I copied the dill._dill.py and dill._shims.py files from this page https://github.com/uqfoundation/dill/tree/master/dill into my conda environment. It worked but I still have the VusuibTransformer issue.

**Comment by ohwi** [comment]
I don't know whether this is the proper way to solve this, but I bypassed this problem with the code below.

```
import io
import pickle
import pickletools


def load_g_ema(network_pkl):
    with open(network_pkl, "rb") as handle:
        d_starts = -1
        g_ema_starts = -1

        # assumes that networks are saved in
        # the order of 'G', 'D', 'G_ema'
        for i, op in enumerate(pickletools.genops(handle)):
            if op[0].name == "BINUNICODE":
                if op[1] == 'D':
                    d_starts = op[2]
                elif op[1] == 'G_ema':
                    g_ema_starts = op[2]

        assert d_starts >= 0 and g_ema_starts >= 0

    with open(network_pkl, 'rb') as handle:
        bs = handle.read()
        bs = bs[:d_starts] + bs[g_ema_starts:]
        obj = pickle.Unpickler(io.BytesIO(bs)).load()

    return obj['G_ema']
```

The point of problem is in the discriminator and discriminator is not what we need for superres training or generation. So I parsed and removed the part related to the discriminator in the pickle file.

I could start superres training with replacing the code
```
with dnnlib.util.open_url(path_stem) as f:
    G_stem = legacy.load_network_pkl(f)['G_ema']
```
to
```
G_stem = load_g_ema(path_stem)
```
in the file `networks_stylegan3_resetting.py`.


Similarly, I could generate images with trained model by replacing checkpoint loading part in the file `gen_images.py`:

![seed0011](https://user-images.githubusercontent.com/22569365/174427989-f73add07-037f-4364-9acd-749f03f8e6ff.png) ![seed0005](https://user-images.githubusercontent.com/22569365/174427998-017eee10-37ee-46c5-a652-4386b94edb4b.png) ![seed0006](https://user-images.githubusercontent.com/22569365/174428002-ce0d6632-1b8d-44e6-874f-3e306a907016.png) ![seed0016](https://user-images.githubusercontent.com/22569365/174428030-6a7133be-b66e-428b-92da-3f6b16cff470.png)


Hope this helps

**Comment by nicholasjprimianomd** [comment]
> 

Could you help me understand what you did here a little more? How did you use the first functions you wrote? And what part of the pickle file did you remove?

**Comment by ohwi** [comment]
For example, in the file `gen_images.py` line 97-99 are for loading trained weight:
```
with dnnlib.util.open_url(network_pkl) as f:
    G = legacy.load_network_pkl(f)['G_ema']
    G = G.eval().requires_grad_(False).to(device)
```

I changed this part to
```
G = load_g_ema(network_pkl)
G = G.eval().requires_grad_(False).to(device)
```

You can just replace the part that loads `G_ema` like the above.


About the pickle file, we know that the pickled file is a dictionary and `D` is the key for discriminator. So I tried to find the point where the information about discriminator starts (which is `d_starts`) and the point where the information `G_ema` starts (which is `g_ema_starts`). Since what we need is `G_ema` I removed things between them and unpickled.

Actually, this is the first time that I tried to load only the part of the pickle file and I believe that there exists a better way to solve this. Though I could not fully understand it, I did a job based on this [link](https://stackoverflow.com/a/26395638), so reading this link may help you to understand the code.

**Comment by nicholasjprimianomd** [comment]
Did you run first function on network-snapshot.pkl? When I do that op[1] gives me the entire file.

**Comment by ohwi** [comment]
Yes, I ran the first function on `network-snapshot.pkl`, which is the training process output.

**Comment by swing148** [comment]
> For example, in the file line 97-99 are for loading trained weight:`gen_images.py`
> 
> ```
> with dnnlib.util.open_url(network_pkl) as f:
>     G = legacy.load_network_pkl(f)['G_ema']
>     G = G.eval().requires_grad_(False).to(device)
> ```
> 
> I changed this part to
> 
> ```
> G = load_g_ema(network_pkl)
> G = G.eval().requires_grad_(False).to(device)
> ```
> 
> You can just replace the part that loads like the above.`G_ema`
> 
> About the pickle file, we know that the pickled file is a dictionary and is the key for discriminator. So I tried to find the point where the information about discriminator starts (which is ) and the point where the information starts (which is ). Since what we need is I removed things between them and unpickled.`D``d_starts``G_ema``g_ema_starts``G_ema`
> 
> Actually, this is the first time that I tried to load only the part of the pickle file and I believe that there exists a better way to solve this. Though I could not fully understand it, I did a job based on this [link](https://stackoverflow.com/a/26395638), so reading this link may help you to understand the code.

Hello,I improved according to your code, but reported this error.
Traceback (most recent call last):
  File "gen_images.py", line 152, in <module>
    generate_images() # pylint: disable=no-value-for-parameter
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "gen_images.py", line 126, in generate_images
    G = load_g_ema(network_pkl)
  File "gen_images.py", line 42, in load_g_ema
    assert d_starts >= 0 and g_ema_starts >= 0
AssertionError

**Comment by woctezuma** [comment]
Basically, the error states that this condition is not met:
```python
assert d_starts >= 0 and g_ema_starts >= 0
```

This happens if at least one of the if-statements (`op[1] == 'D'` or `op[1] == 'G_ema'`) is not triggered, or if the value is negative:
```python
        d_starts = -1
        g_ema_starts = -1

        # assumes that networks are saved in
        # the order of 'G', 'D', 'G_ema'
        for i, op in enumerate(pickletools.genops(handle)):
            if op[0].name == "BINUNICODE":
                if op[1] == 'D':
                    d_starts = op[2]
                elif op[1] == 'G_ema':
                    g_ema_starts = op[2]
```
